### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by huangkun101230** [HAL-lucination/segfuse#1]
Hi,

I tried to run your code on my machine, but I got these:

Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "main.py", line 107, in main
    saver.LoadLatestModel(model, None)
  File "C:\Users\GGPC\Desktop\segfuse\Utils\ModelSaver.py", line 36, in LoadLatestModel
    params = torch.load(name)
  File "C:\Users\GGPC\miniconda3\envs\segfuse\lib\site-packages\torch\serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\GGPC\miniconda3\envs\segfuse\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Could you please help me with this problem?

**Comment by Shmnl** [comment]
I get the same error. I am unsure if the saved model leads to this problem, but is it possible to provide a new pkl file?

**Comment by Renatusphere** [comment]
I'm confronted with the same problem. Have you found a way to solve it?

**Comment by COATZ** [comment]
Same here! Did you find a workaround?

**Comment by zcyyyy24** [comment]
> Hi,
> 
> I tried to run your code on my machine, but I got these:
> 
> Traceback (most recent call last): File "main.py", line 111, in main() File "main.py", line 107, in main saver.LoadLatestModel(model, None) File "C:\Users\GGPC\Desktop\segfuse\Utils\ModelSaver.py", line 36, in LoadLatestModel params = torch.load(name) File "C:\Users\GGPC\miniconda3\envs\segfuse\lib\site-packages\torch\serialization.py", line 600, in load with _open_zipfile_reader(opened_file) as opened_zipfile: File "C:\Users\GGPC\miniconda3\envs\segfuse\lib\site-packages\torch\serialization.py", line 242, in **init** super(_open_zipfile_reader, self).**init**(torch._C.PyTorchFileReader(name_or_buffer)) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> Could you please help me with this problem?

Did you put the pretrained model in the save folder？In this way, I ran it successfully and got depth data.
![image](https://github.com/HAL-lucination/segfuse/assets/152855926/6619c263-05f9-4231-ace6-1a0f7590f9a7)

**Comment by Thryrallo** [comment]
hi, same problem. Has this been solved yet?
